name: CraftyServerSystem
main: me.devtec.craftyserversystem.Loader
authors: [Straikerinos,Darqes]
softdepend: [TheAPI,Vault,LuckPerms,PlaceholderAPI]
web: https://spigotmc.org/resources/71147/
version: 1.1.1
api-version: '1.13'